### ISSUE TITLE
Add ability to show team time differences as gap to leader

### ISSUE THREAD

**Issue by MLSTRM** [MLSTRM/relay-controller#21]
Rather than showing both available comparisons in either direction, the ability to only show the difference to the "leading" team would be beneficial to reduce info overhead.

**Comment by MLSTRM** [comment]
This probably just needs a new overload/functionality piece on VersusWrapper to take multiple comparisons and only show the largest.
Also ability to hide negative values for the other side here.

**Comment by Mrzwanzig** [comment]
Added in ee7a40b3e678ff20782de48ca2ac6f3fd24297a4
