### ISSUE TITLE
Ability to turn on versus wrappers to the runner info screen

### ISSUE THREAD

**Issue by MLSTRM** [MLSTRM/relay-controller#22]
To enable the layout we want for relay 6, we need the versus wrappers on the name view rather than the split view.

**Comment by Mrzwanzig** [comment]
Option to toggle this added in a0a864c94f2a1f85c0c417dc7eb5c2fb708fdaf5

Currently, if the option to display the versus wrappers on the split view is turned on, they will not actually display since the current (hardcoded) layout is not built around it.
