### ISSUE TITLE
Adjust formatting options to allow for different alignment properties OR hardcode layout changes for relay 6

### ISSUE THREAD

**Issue by MLSTRM** [MLSTRM/relay-controller#23]
As per title. Need ability to left align text and potentially change vertical spacing. Ideally should be done through the meta file, but can be hardcoded/hacked in for now if needed.

**Comment by Mrzwanzig** [comment]
Added in 4c19fde75194452890d76e279574eb922bb52346

**Comment by MLSTRM** [comment]
Hardcoded for the most part.
